[features]
seeds = false
skip-lint = false

[programs.localnet]
crate = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
crate = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.mainnet]
crate = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "cp target/idl/crate.json app/src/idl/crate.json"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB"  # Jupiter
[[test.validator.clone]]
address = "So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo"  # Solend
[[test.validator.clone]]
address = "DjVE6JNiYqPL2QXyCUUh8rNjHrbz9hXHNYt99MQ59qw1"  # Orca

[workspace]
members = [
    "programs/crate"
]

[commands]
deploy = "anchor deploy --provider.cluster devnet"
build = "anchor build"
test = "anchor test"
localnet = "anchor localnet"
